### ISSUE TITLE
Camel Editor in Oxygen reformats source after switching from design to source tabsheet

### ISSUE THREAD

**Issue by ronnyaerts** [jbosstools/jbosstools-fuse#1002]
I just installed the latest Oxygen with "JBoss Fuse Tooling Apache Camel Editor" (from the "JBoss Tools 4.5.0.AM1"). 
I now notice (but I think previous versions already have the same issue) that when I open my camel context file, the "design" tabsheet is opened. I don't use the visual editor and always use the "Source" tab. I notice that my camel context xml is reformated (or ever completely rewitten) when I switch from the design to the source tab and that is unexpected behaviour because I want to keep the source xml as is. I see for a short moment the original source but it gets reformated after a second or so. Tabs are replaced by spaces. Empty lines are removed. See attachment. 
![2017-07-07_11h55_02](https://user-images.githubusercontent.com/6245529/27953210-3f48acc4-630b-11e7-8f1e-a4cb17d6a420.png)

My design is even completely empty (and therefore useless) because I only use route context files. 

Can I somehow prevent this reformatting of the source? Or can I directly open the source tab when I open a file?

**Comment by lhein** [comment]
Hi Ronny,

thanks for reporting this issue. We already know about that one. It is caused by the XML Writer. We will investigate how to preserve your formatting. I raised a Jira issue for you to track at https://issues.jboss.org/browse/FUSETOOLS-2438

Lars

**Comment by apupier** [comment]
Hi Ronny,

As a workaround, to help you leverage other functionalities provided by Fuse Tooling, what do you think to use the classical XML editor if you are not using the graphical editor?

You can use with XML editor with right-clicking on the file:
![image](https://user-images.githubusercontent.com/1105127/27959850-63fdfd94-6329-11e7-95b0-0bc07384bf1f.png)


Regards,

**Comment by lhein** [comment]
closing this old issue
