### ISSUE TITLE
Test sources added to war when RouteBuilder used

### ISSUE THREAD

**Issue by arsou33** [jbosstools/jbosstools-fuse#1147]
When RouteBuilder is used in a War project under Eclipse, test sources are added to Deployment Assembly.
Seems error come from : https://github.com/jbosstools/jbosstools-fuse/blame/master/editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/maven/CamelProjectConfigurator.java#L123.

**Comment by lhein** [comment]
Thanks for reporting the issue. We are looking at it.

**Comment by lhein** [comment]
issue tracked at https://issues.jboss.org/browse/FUSETOOLS-2711

**Comment by apupier** [comment]
the issue has been fixed and will be available in next Fuse Tooling (10.2.0) Planned to be publicly available at the very end of January.

Thanks @asrou33 for your report.
