### ISSUE TITLE
java.lang.NullPointerException at org.fusesource.ide.launcher.debug.model.CamelDebugTarget.generateKey(CamelDebugTarget.java:212)

### ISSUE THREAD

**Issue by cdmaslo** [jbosstools/jbosstools-fuse#1565]
## My Environment
Latest Red Hat CodeReady Studio - 12.12.0.GA fresh installation running latest jdk1.8.0_211 on Windows 10

## Expected Behaviour

Debugger stopped and showing variables

## Actual Behaviour

The debugger starts, not showing variables and not showing the current step and with exception
`java.lang.NullPointerException
	at org.fusesource.ide.launcher.debug.model.CamelDebugTarget.generateKey(CamelDebugTarget.java:212)
	at org.fusesource.ide.launcher.debug.model.EventDispatchJob.handleSuspendedBreakpoints(EventDispatchJob.java:80)
	at org.fusesource.ide.launcher.debug.model.EventDispatchJob.checkSuspendedBreakpoints(EventDispatchJob.java:56)
	at org.fusesource.ide.launcher.debug.model.EventDispatchJob.run(EventDispatchJob.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`
## Steps to Reproduce

Use any camel route with <removeHeaders id="_removeHeaders1" pattern="*"/> and add breakpoint after this step

##Possible solution
There is a missing check in
```java
public String generateKey(BacklogTracerEventMessage msg) {
    if (msg == null) {
      return null;
    }
    final List<Header> headers = msg.getMessage().getHeaders();
    for (IBacklogTracerHeader h : headers) {
      if ("breadcrumbid".equalsIgnoreCase(h.getKey())) {
        // there is a breadcrumbId - use that as key
        return h.getValue();
      }
    }
    // otherwise use the exchange id
    return msg.getExchangeId();
  }
```
Headers variable contains null, when there are no errors. So suggested code is
```java
public String generateKey(BacklogTracerEventMessage msg) {
    if (msg == null) {
      return null;
    }
    final List<Header> headers = msg.getMessage().getHeaders();
    if (headers != null) {
      for (IBacklogTracerHeader h : headers) {
        if ("breadcrumbid".equalsIgnoreCase(h.getKey())) {
          // there is a breadcrumbId - use that as key
          return h.getValue();
        }
      }        
    }
    // otherwise use the exchange id
    return msg.getExchangeId();
  }
```

**Comment by apupier** [comment]
@cdmaslo Thanks for reporting the issue and providing a possible fix. Can you precise which route and which version of Camel you are using please?
I cannot reproduce a case where the headers are null.

I usually have 10 headers, something like
[CamelFileAbsolute=false, CamelFileAbsolutePath=C:\install\eclipse-committers-2019-03-R-win32-x86_64\eclipse\ws_fusetooling_win_dev\7.3.1-karaf\work\cbr\input\ID-DESKTOP-XXX-1563181443813-0-6, CamelFileLastModified=1563181606055, CamelFileLength=1305, CamelFileName=ID-DESKTOP-XXX-1563181443813-0-6, CamelFileNameConsumed=ID-DESKTOP-9NT300B-1563181443813-0-6, CamelFileNameOnly=ID-DESKTOP-XXX-1563181443813-0-6, CamelFileParent=work\cbr\input, CamelFilePath=work\cbr\input\ID-DESKTOP-9NT300B-1563181443813-0-6, CamelFileRelativePath=ID-DESKTOP-9NT300B-1563181443813-0-6, breadcrumbId=ID-DESKTOP-XXX-1563181443813-0-7]

**Comment by cdmaslo** [comment]
Hallo,
to reproduce it, simply add 
```xml
<removeHeaders id="_removeHeaders1" pattern="*"/>¨
``` 
to your route.
We already removed such pattern, as it is anyway a bad idea. But someone else could repeat our mistake.

Thanks a lot,
Als

**Comment by apupier** [comment]
Thanks for the precisions. I tried with the fix and detected no other issues.
Not added a test case as it seems to be really a very rare/border case (you even mentioned that it is a bad idea :-) )
Thank you for reporting it.
