### ISSUE TITLE
Camel 3.x use with Latest Fuse IDE only shows route objects

### ISSUE THREAD

**Issue by sschotte** [jbosstools/jbosstools-fuse#1737]
## Your Environment

- my operating system and version - Windows 10 Enterprise(version: 20H2), 64 bit
- used Development IDE and version - Eclipse 4.20
- used Fuse Tooling version - JBoss Tools 4.21.0 Final
- used Java JDK Version and Name - AdoptOpenJDK 11

## Expected Behaviour

Camel Context design tab should show a complete route diagram. However it only shows route objects.
We were using a Camel Context Spring DSL file migrated from Camel 2.21 to Camel 3.11.2

## Actual Behaviour

Camel Context design tab is not showing up a complete route diagram and a warning appears on the route that says "Parameter input is a mandatory field and cannot be empty."

## Steps to Reproduce

Please describe the exact steps to reproduce the issue you encountered...

![CamelContext_View_Only_Routes](https://user-images.githubusercontent.com/40454714/142187627-e671957b-018c-4233-a68d-942b43d8d80e.png)
1. Create a Camel Spring DSL project with camel version 3.11.2
2. Create a camel context xml file with a route having few endpoints.
3. Switch to design tab to check if route diagram is visible.

**Comment by lhein** [comment]
Atm we do not have Camel 3.x support. I'd recommend to open a jira at https://issues.redhat.com/projects/FUSETOOLS.

**Comment by siddhikhapare** [comment]
@sschotte @lhein I would like to work on this issue. I have gone through document of redhat setting environment. May I install  Red Hat Developer Studio? How can I do setup to work on this issue? Do I install above mentioned requirements?

**Comment by apupier** [comment]
Hi @siddhikhapare ,
to work on this you will need to setup a development environment for an Eclipse RCP application. Some information can be found here https://github.com/jbosstools/jbosstools-fuse/blob/master/Contributing.md (not sure that they are very up to date).

**Comment by siddhikhapare** [comment]
@apupier Thank you. I will look into it.

**Comment by apupier** [comment]
@sschotte I know it is a long time but can you share the file to reproduce the issue? or be able to provide a simple reproducer?

**Comment by Mona987654321** [comment]
@apupier : Add any camel Context file named as camelContextSample.xml . Providing you the  sample snippet:
![MicrosoftTeams-image (55)](https://github.com/jbosstools/jbosstools-fuse/assets/133361410/a92a8bdd-26ea-482c-9b4f-a010740a9907)



Check the design tab
![MicrosoftTeams-image (54)](https://github.com/jbosstools/jbosstools-fuse/assets/133361410/eff1a808-ad6a-4588-a67c-a5bad8b54d55)


Note: I have used Spring XML DSL.

**Comment by geetha179** [comment]
The said issue is still there in after using the snapshot version provided.

In the meantime, We have upgraded our projects to Apache Camel to 3.21 and Route templates with XML DSL. Only empty page is appearing in design tab when route template xml files are opened.

**Comment by apupier** [comment]
Route templates is a new feature and I have not worked to support it.
